# Generated by Django 3.2.6 on 2021-08-29 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.TextField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=300)),
                ('date_purchased', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
