# Generated by Django 3.2.6 on 2021-08-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.CharField(max_length=100),
        ),
    ]
