# Generated by Django 3.2.6 on 2021-08-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210830_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customers',
            new_name='consumer',
        ),
    ]
