# Generated by Django 3.2.6 on 2021-08-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_customers_consumer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consumer',
        ),
    ]
