# Generated by Django 3.2.6 on 2021-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_consumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('mode_of_payment', models.CharField(max_length=100)),
            ],
        ),
    ]
