# Generated by Django 3.2.6 on 2021-08-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_name_consumer_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='names',
            new_name='namez',
        ),
    ]
